
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'HumanData')
BEGIN
	CREATE TABLE HumanData
	(
		Id			INT
		,Nombre		VARCHAR(64)
		,Sexo		VARCHAR(1)
		,Altura		DECIMAL(2,2)
		,Peso		DECIMAL(2,2)
		CONSTRAINT		    [PK_Id_HumanData] PRIMARY KEY CLUSTERED
	    (
		   [Id]   ASC
	    )
	    WITH (PAD_INDEX					= OFF,
				STATISTICS_NORECOMPUTE	= OFF,
				IGNORE_DUP_KEY			= OFF,
				ALLOW_ROW_LOCKS			= ON,
				ALLOW_PAGE_LOCKS		= ON)
	    ON [PRIMARY]
	)   ON [PRIMARY];
END